version: '3'

services:
  mosquitto:
    container_name: mosquitto
    image: iegomez/mosquitto-go-auth
    volumes:
      - ./mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto/conf.d:/mosquitto/conf.d
    ports:
      - 127.0.0.1:1883:1883

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: example
    volumes:
      - ./docker/data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: sbiot
    environment:
      APP_PORT: 4000
      PG_USERNAME: postgres
      PG_PASSWORD: example
      PG_HOST: db
      PG_PORT: 5432
      PG_DB: example
      JWT_TTL: 32
      JWT_SECRET: suttapakmatee
      BCRYPT_SALT: 11
      MQTT_PORT: 1883
      MQTT_BROKER: mosquitto
      MQTT_USERNAME: 225166bd-8ce8-4bb4-af0d-09c3c4e0ec79
      MQTT_PASSWORD: spider09
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - ./docker/backend/public:/public
    depends_on:
      - db

  frontend:
    container_name: swiot
    build: ./web
    ports:
      - 127.0.0.1:3000:80
    volumes:
      - ./docker/web:/app
    depends_on:
      - backend
