app:
  port: 4000

pg:
  username: 'postgres'
  password: 'example'
  host: '127.0.0.1'
  port: 5432
  db: 'example'

jwt:
  ttl: 32
  secret: 'suttapkamatee'

bcrypt:
  salt: 11

mqtt:
  port: 1883
  broker: "127.0.0.1"
  username: "fd3782ff-a373-4146-8534-b85f78a78aa7"
  password: "spider09"